{% set version = '2013.9-1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-setrng
  version: {{ version|replace("-", "_") }}

source:
  fn: setRNG_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/setRNG_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/setRNG/setRNG_{{ version }}.tar.gz
  sha256: 1a1a399682a06a5fea3934985ebb1334005676c6a2a22d06f3c91c3923432908

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('setRNG')"           # [not win]
    - "\"%R%\" -e \"library('setRNG')\""  # [win]

about:
  home: http://distr.r-forge.r-project.org/
  license: GPL-2
  summary: SetRNG provides utilities to help set and record the setting of the seed and the uniform
    and normal generators used when a random experiment is run. The utilities can be
    used in other functions  that do random experiments to simplify recording and/or
    setting all the  necessary information for reproducibility.  See the vignette and
    reference manual for examples.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
