travis:
  secure:
    BINSTAR_TOKEN: pf7bUL16NAa8zugg9LwvU9RysBVTUOt4NloigrxKVYa6RlgsOHBNc+fBzFG6YVxODpXeKrvX1tIIf3gLhQo5gI0eqZbggS0JmYqJL9/dTbFZMNgGR8P/yhG/6A/eujXoVULn4wGpQe3uz/j9bYsCREGrtKI6Tb3ou4c0WZLXuDt/Mq3BnMin+M5RTK4WcVasKGXSF8bIIDqfMu6pvEQwIWtvcR6gtnHahKzTP/fzXHqbLa4a+bpAFunSPdegfqoILXY6iq+VmnJGPQsvQ1QYml4P62mLAaEeCF5uDq+q/aB6qxnRlI8sT3q9H7YnkD0P0Id3yi7pCaiKfmBRHJK12Ph5PkcprpfnQ6ly/AZVZ3XSCN87KjzhDre5GYn6tmVxCzBLb2NfQ19f8qVbc7hvkSt2/2OpgFTvIv+IukdANLTKfzoDisnEwpZ1m8GEmuA8fmJPEUowwWRa1CubpMozrXGcW2T9uOyOVzt6Kcsv9Wn3FQX919qCZ4rlPxTvjh6VrUUPz/D8J+PBefrZ8XBTS23iJnwP1vvS67tX+PkhHRloOdl5Vx3gDsoNapq+GFgQ77SMnnD7RyCX0P48wCI4PhOF3wbgNMDep7wui7DlbGKhlceGQ7NrrJMG/iJWKGCrNc38oHS7PD7ROluhCFU6i8MYHC+yzKB9aIRnPVCaBZc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
