appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lBPzbfLlcCXJAX79jrI/HDa53JWx13lf04WcEVLA3mMwWpeWojp0rgOTsEO+CXavL7H9DbMu4mQ7/aEYYIkUXyKe9B6zHP6WE0m1roxIpOH6bstxOrnHGgEo7FXLti5pevFEy50I/e6HbwRK1PNy5ZqwxPNF3OC3VvfLeagFcZIOuQcd0AEFFdKNfQiGgMXGImJ4ShPK4+b4c1Rw2JhufCQhNmoXa3bwp0snx/fpikFu/CwGyG19fMqW+LILr3O7wkcXTynCLh1zQlMWRgprH/lcjHiPyOb7ckkMrbsgJGYmW8HHcOBT0mQZP+e13tPQhh43rPjnnzwlHIV8ZABUpj/0RDJo2Olm72yVbxmz31DR4ODNc+S8Zoc+7Icc1DmfLx2/hkhix6DfGozuVIRCVHndSExe0sYjvao1mopb9KTybf/onwtctRqhbuGdT7I6J/SmTZynOTECnFMC7h1Un+BydxlGW4S/tdQ+xzlP0+NkscqSX3cD+947keJlwWgs9HfclPBrI822JW5mp4OEKy2zs0hSaea04ihZO1LVk6xd4ztFMV1zM3QNvywo+fcx0bpfOFOBGW8EUfupLW21p2EppUqjFSq8w6dq2dDlDGE0vl0qMkl+drOxHTg8TABTED7p7AFRf1rRi+F+T0UqW+6Zj3Wrj34EfCh6Xc6Uhmg=
conda_forge_output_validation: false
