travis:
  secure:
    BINSTAR_TOKEN: bKjzGzu14aM2o9v/Rt+iZmyg+ktYsYemfTgr29vj6SfzNkx5cWW6DrmNdhUlZXnLwJuNXF+zrVsYKm9fzFfGyhTmoFookeURhLrMOWE5XBYTnaqOdwKT1ftabq5zxLO4T84UqYGKOngDkYF3ijBC2JriBQiG1XOMm7YXwX/SFemhPNlA4stDudb66bC/VXnrtCh2POLFfFQwUM9fC4+/Xr2Upfqq/FBA2Ak5Xd85CbHzG1+RF45zP8ewfAoS/xTBtUrQdFhkWFvuNzjdQFMuj5vZryJZ3ESl1TGiuYP2otYJb0yvJw15ayGv+Fm8WOIy34cNBAyFIdse4v/7+QgY/NwmSoxAgA6z7FR1DOCbYZY4O/yWdm4DDk8xg0Cv7yibRQx+Lv9H56xc8tQtysUbmR8n+i7JSazQ/byECevn/jL2B+/BWYPbS2Bakq8Y54yaI0Nidbya9Ic4ch7kNFzilDxdtUob0nkSBZmFdw89dyPXLjeYpnEWCHfR98SyxpkyFNdVICqfHp1eLGIWLf1KIo7XXZMA0EjAPsLhgvl4D0twUNxXZo1pQ7lo6Q2kfmXRqY+YdFEn6JcgjVfPPSu3OQRqaLscQ6uOycCgjfGnmtuicb3E/tXZZQ5W20Qkx6RSyd4JSAImJwlpa+ZT/fgf1e88E4OCmiLqb8jjdE6YIhQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
